// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZUeAg6BocicJu9FWzkTXux2JIioCfaVQ',
    appId: '1:1031688894365:web:37440c08c2f5d4997da174',
    messagingSenderId: '1031688894365',
    projectId: 'smart-plant-care-fyp-2026',
    authDomain: 'smart-plant-care-fyp-2026.firebaseapp.com',
    storageBucket: 'smart-plant-care-fyp-2026.firebasestorage.app',
    measurementId: 'G-LDW00CVPLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPoUhpPEE-15YPx7AfJa1OU45ayBgYSPA',
    appId: '1:1031688894365:android:d7466dfb06e90b6a7da174',
    messagingSenderId: '1031688894365',
    projectId: 'smart-plant-care-fyp-2026',
    storageBucket: 'smart-plant-care-fyp-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAilSgmOpsuhCBgXwmnkIeEaVoaGRVpC1E',
    appId: '1:1031688894365:ios:92e04c266df51b347da174',
    messagingSenderId: '1031688894365',
    projectId: 'smart-plant-care-fyp-2026',
    storageBucket: 'smart-plant-care-fyp-2026.firebasestorage.app',
    iosBundleId: 'com.example.smartPlantCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAilSgmOpsuhCBgXwmnkIeEaVoaGRVpC1E',
    appId: '1:1031688894365:ios:92e04c266df51b347da174',
    messagingSenderId: '1031688894365',
    projectId: 'smart-plant-care-fyp-2026',
    storageBucket: 'smart-plant-care-fyp-2026.firebasestorage.app',
    iosBundleId: 'com.example.smartPlantCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZUeAg6BocicJu9FWzkTXux2JIioCfaVQ',
    appId: '1:1031688894365:web:59831f6a862224577da174',
    messagingSenderId: '1031688894365',
    projectId: 'smart-plant-care-fyp-2026',
    authDomain: 'smart-plant-care-fyp-2026.firebaseapp.com',
    storageBucket: 'smart-plant-care-fyp-2026.firebasestorage.app',
    measurementId: 'G-GL7HGZK0HH',
  );
}
